from turtle import Turtle


class Message(Turtle):
    def __init__(self):
        super().__init__()
        self.speed(9)
        self.pencolor("white")
    
    def game_over(self):
        self.width(10)
        self.penup()
        self.goto(-250, 40)
        self.setheading(180)
        self.pendown()
        self.forward(40)
        self.left(90)
        self.forward(80)
        self.left(90)
        self.forward(40)
        self.left(90)
        self.forward(40)
        self.left(90)
        self.forward(10)

        self.penup()
        self.goto(-220, -40)
        self.pendown()
        self.setheading(90)
        self.forward(80)
        self.right(90)
        self.forward(40)
        self.right(90)
        self.forward(80)
        self.penup()
        self.goto(-220, 0)
        self.pendown()
        self.setheading(0)
        self.forward(40)

        self.penup()
        self.goto(-150, -40)
        self.pendown()
        self.setheading(90)
        self.forward(80)
        self.setheading(300)
        self.forward(50)
        self.setheading(60)
        self.forward(50)
        self.setheading(270)
        self.forward(80)

        self.penup()
        self.goto(-70, 40)
        self.pendown()
        self.setheading(270)
        self.forward(80)
        self.backward(80)
        self.setheading(0)
        self.forward(40)
        self.penup()
        self.goto(-70, 0)
        self.pendown()
        self.forward(40)
        self.penup()
        self.goto(-70, -40)
        self.pendown()
        self.forward(40)

        self.penup()
        self.goto(70, 40)
        self.pendown()
        self.setheading(180)
        self.forward(40)
        self.setheading(270)
        self.forward(80)
        self.setheading(0)
        self.forward(40)
        self.setheading(90)
        self.forward(80)

        self.penup()
        self.goto(100, 40)
        self.pendown()
        self.setheading(285)
        self.forward(85)
        self.setheading(75)
        self.forward(85)

        self.penup()
        self.setheading(0)
        self.forward(30)
        self.pendown()
        self.setheading(270)
        self.forward(80)
        self.backward(80)
        self.setheading(0)
        self.forward(40)
        self.penup()
        self.goto(174, 0)
        self.pendown()
        self.forward(40)
        self.penup()
        self.goto(174, -40)
        self.pendown()
        self.forward(40)

        self.penup()
        self.goto(244, 40)
        self.pendown()
        self.setheading(270)
        self.forward(80)
        self.backward(80)
        self.setheading(0)
        self.forward(40)
        self.right(90)
        self.forward(40)
        self.right(90)
        self.forward(40)
        self.goto(284, -40)

    def you_won(self):
        self.write("You Won!", align="center", font=("Arial", 80, ""))